package com.sample
 
import co.uniandes.KM.logicPuzzles.UI.DroolsTest.Message;
import co.uniandes.KM.logicPuzzles.mundo.*;
		
rule "Positive elimination"
	when
		c : Cell( status == Cell.UNKNOWN )
	then
		System.out.println( "I'm a strong independent cell" );
end

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
